"""empty message

Revision ID: 591c56ed2dac
Revises: fd4c7967176f
Create Date: 2021-05-11 17:33:26.055615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591c56ed2dac'
down_revision = 'fd4c7967176f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('traderId', sa.Integer(), nullable=False))
    op.add_column('trades', sa.Column('uniqueTradeId', sa.String(length=36), nullable=False))
    op.drop_constraint('unique_trade', 'trades', type_='unique')
    op.create_unique_constraint('unique_trade', 'trades', ['traderId', 'makerCurrencyId', 'takerCurrencyId', 'quantity', 'bidOrOffer', 'price', 'created_on'])
    op.create_unique_constraint(None, 'trades', ['uniqueTradeId'])
    op.drop_constraint('trades_takerId_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('trades_makerId_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'users', ['traderId'], ['id'])
    op.drop_column('trades', 'makerId')
    op.drop_column('trades', 'takerId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('takerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('makerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_makerId_fkey', 'trades', 'users', ['makerId'], ['id'])
    op.create_foreign_key('trades_takerId_fkey', 'trades', 'users', ['takerId'], ['id'])
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_constraint('unique_trade', 'trades', type_='unique')
    op.create_unique_constraint('unique_trade', 'trades', ['makerId', 'takerId', 'makerCurrencyId', 'takerCurrencyId', 'quantity', 'bidOrOffer', 'price', 'created_on'])
    op.drop_column('trades', 'uniqueTradeId')
    op.drop_column('trades', 'traderId')
    # ### end Alembic commands ###
