"""empty message

Revision ID: fd4c7967176f
Revises: 8d000b7ee8c0
Create Date: 2021-05-11 16:55:08.186098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4c7967176f'
down_revision = '8d000b7ee8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trades_postId_key', 'trades', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trades_postId_key', 'trades', ['postId'])
    # ### end Alembic commands ###
