"""empty message

Revision ID: 271520156ed4
Revises: 591c56ed2dac
Create Date: 2021-05-12 18:48:35.174597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271520156ed4'
down_revision = '591c56ed2dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trades_uniqueTradeId_key', 'trades', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trades_uniqueTradeId_key', 'trades', ['uniqueTradeId'])
    # ### end Alembic commands ###
