"""empty message

Revision ID: 6cb872ac7fdf
Revises: 561fc77fbe50
Create Date: 2021-05-05 16:38:40.952245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb872ac7fdf'
down_revision = '561fc77fbe50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_trade', 'trades', type_='unique')
    op.create_unique_constraint('unique_trade', 'trades', ['makerId', 'takerId', 'makerCurrencyId', 'takerCurrencyId', 'quantity', 'bidOrOffer', 'price', 'created_on'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_trade', 'trades', type_='unique')
    op.create_unique_constraint('unique_trade', 'trades', ['makerId', 'takerId', 'makerCurrencyId', 'takerCurrencyId', 'created_on'])
    # ### end Alembic commands ###
