"""empty message

Revision ID: 24a796a43208
Revises: b6ea8476cbe6
Create Date: 2021-05-05 14:13:03.840888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a796a43208'
down_revision = 'b6ea8476cbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('bidOrOffer', sa.String(length=5), nullable=False))
    op.add_column('trades', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'quantity')
    op.drop_column('trades', 'bidOrOffer')
    # ### end Alembic commands ###
