"""empty message

Revision ID: b6ea8476cbe6
Revises: ffdc0a98111c
Create Date: 2021-05-04 14:47:10.574524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ea8476cbe6'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencyPair', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currencyPair')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('currencyId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bidOrOffer', sa.String(length=5), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currencyId'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'currencyId', 'price', 'bidOrOffer', 'created_on', 'updated_on', name='unique_post')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('makerId', sa.Integer(), nullable=False),
    sa.Column('takerId', sa.Integer(), nullable=False),
    sa.Column('currencyId', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currencyId'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['makerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['takerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('makerId', 'takerId', 'currencyId', 'created_on', name='unique_trade')
    )
    op.create_table('userBalances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('currencyId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currencyId'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userBalances')
    op.drop_table('trades')
    op.drop_table('posts')
    op.drop_table('currencies')
    # ### end Alembic commands ###
