"""empty message

Revision ID: c2449694aafb
Revises: 7e6d30281d0d
Create Date: 2021-05-05 15:14:34.944245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2449694aafb'
down_revision = '7e6d30281d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'price')
    # ### end Alembic commands ###
